apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
         - name: CONFIGMAP_USERNAME
           valueFrom:
             configMapKeyRef:
               name: myconfigmap
               key: username

      volumes:
       - name: secret-volume
         secret:
           secretName: dotfile-secret

